spring:
  application:
    name: backend
#server:
#  address: 192.168.1.64

  datasource:
    url: jdbc:postgresql://localhost:5432/movies_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
     hibernate:
        ddl-auto: create
     show-sql: true